name: Publish (Pages)

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        if: github.repository_owner == 'dragonfruitnetwork'
        with:
          branch: live
          folder: ${{ env.GITHUB_WORKSPACE }}/public
          git-config-name: "Yuna"
          git-config-email: "inbox@dragonfruit.network"
