name: Publish (Pages)

permissions:
  contents: read
  pages: write
  id-token: write

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Pages
        uses: actions/configure-pages@v1
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.BUILD_OUTPUT }}/public
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
