name: Publish

permissions:
  contents: read
  pages: write
  id-token: write

on:
  release:
    types: [ published ]

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  pages:
    runs-on: windows-latest
    
    environment:
      name: production
      url: https://d6static.dragonfruit.network

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup ImageMagick
        run: choco install imagemagick
        
      - name: Setup PowerShell Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
        
      - name: Process Assets
        run: ./process-assets.ps1
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
